print('Welcome to the Mad Lib Generator!')
print('')
adjective_1 = raw_input('Type in an adjective: ')
adjective_2 = raw_input('Another adjective: ')
adjective_3 = raw_input('And another adjective: ')
adjective_4 = raw_input('One more adjective: ')
animals = raw_input('Plural animal (e.g. puppies): ')
verb = raw_input('Now a verb: ')
nouns = raw_input('Now a plural noun: ')
woman_musician = raw_input('The first name of a woman musician: ')
beverage = raw_input('A beverage: ')
body_parts = raw_input('And finally, a plural body part: ')
print('')
print("Excellent choices! Here's your story...")
print('')
print('There once was a fearless programmer named ' + woman_musician)
print('who wanted to build a ' + adjective_2 + ' mobile app to ')
print('help ' + adjective_3 + ' ' + animals + ' find new homes.')
print('')
print(woman_musician + ' stayed up all night, drinking lots of')
print('caffeinated ' + beverage + ' as she worked')
print('trying to complete her fancy program.')
print('')
print('Whenever ' + woman_musician + ' hit a dead end, she would')
print('exclaim *' + nouns + '*!')
print('')
print('But she was not discouraged, and after a quick break')
print('to ' + verb + ' and clear her head, she got back to work.')
print('')
print('By morning, when the sun started to rise, she let out a')
print('big yawn and stretched her ' + body_parts + '.')
print('')
print('Finally, she was done.')
print('---------------------------')